require('user/options')
require('user/cmp')
require('user/keymaps')
require('user/plugins')
require('user/colorscheme')
require('user.lsp')
require('user.telescope')
require('user.treesitter')
require('user.autopairs')
require('user.comment')
require('user.gitsigns')
require('user.nvim-tree')
require('user.bufferline')
require('user.toggleterm')
require('user.nvim-dev-container')
require('dap-python').setup('~/.virtualenvs/debugpy/bin/python')
require('dapui').setup()
--require('plugins')
--require('keymappings')
--require('nv-compe')

-- require'nvim-tree'.setup {}
-- require'nvim-web-devicons'.setup {}
